import type { Agent, AgentId, PlanStep, WorkspaceTask } from './types'

export const agents: Agent[] = [
  {
    id: 'supervisor',
    name: 'AI 管家',
    role: 'Supervisor · 总协调者',
    description: '理解目标、拆解计划，并让合适的 AI 员工协同完成工作。',
    initials: 'AI',
    color: '#e9e5ff',
    accent: '#6558d3',
    icon: 'sparkles',
    skills: ['任务拆解', '动态规划', '异常处理'],
    state: 'working',
    completedTasks: 128,
  },
  {
    id: 'project',
    name: '项目管家',
    role: 'Project Agent · 项目管理',
    description: '聚合项目进度、里程碑和风险，让团队状态一目了然。',
    initials: '项',
    color: '#dcecff',
    accent: '#4088e8',
    icon: 'tasks',
    skills: ['项目进度', '风险识别', '里程碑'],
    state: 'idle',
    completedTasks: 86,
  },
  {
    id: 'data',
    name: '数据分析师',
    role: 'Data Agent · 数据分析',
    description: '连接业务数据，自动完成指标计算、趋势分析和异常发现。',
    initials: '数',
    color: '#d7f4e8',
    accent: '#28a978',
    icon: 'chart',
    skills: ['SQL', '趋势分析', '异常检测'],
    state: 'idle',
    completedTasks: 74,
  },
  {
    id: 'knowledge',
    name: '知识专家',
    role: 'Knowledge Agent · 企业知识',
    description: '从制度、项目文档和会议资料中检索有依据的答案。',
    initials: '知',
    color: '#fff0d9',
    accent: '#d88925',
    icon: 'book',
    skills: ['语义检索', '来源溯源', '知识问答'],
    state: 'idle',
    completedTasks: 112,
  },
  {
    id: 'document',
    name: '文档专家',
    role: 'Document Agent · 文档整理',
    description: '读取和归纳企业文档，把分散信息整理为可用的上下文。',
    initials: '文',
    color: '#f8dff0',
    accent: '#c954a0',
    icon: 'file',
    skills: ['PDF / Word', '信息提取', '对比归纳'],
    state: 'idle',
    completedTasks: 63,
  },
  {
    id: 'meeting',
    name: '会议秘书',
    role: 'Meeting Agent · 会议助手',
    description: '提炼会议决策、行动项和参与人，让讨论自然转成执行。',
    initials: '会',
    color: '#e4e1ff',
    accent: '#7166d8',
    icon: 'calendar',
    skills: ['会议总结', '行动项', '任务生成'],
    state: 'idle',
    completedTasks: 49,
  },
  {
    id: 'writer',
    name: '内容创作师',
    role: 'Writer Agent · 内容生成',
    description: '将结构化事实组织成清晰、适合不同受众的交付内容。',
    initials: '写',
    color: '#ffe0d9',
    accent: '#df6b4f',
    icon: 'file',
    skills: ['报告写作', '管理层表达', '多格式输出'],
    state: 'idle',
    completedTasks: 95,
  },
  {
    id: 'reviewer',
    name: '质量审核员',
    role: 'Reviewer Agent · 质量审核',
    description: '检查证据、口径和表达，发现问题后触发反馈闭环。',
    initials: '审',
    color: '#dcecf6',
    accent: '#377ea5',
    icon: 'shield',
    skills: ['事实核验', '风险检查', '反馈闭环'],
    state: 'idle',
    completedTasks: 119,
  },
  {
    id: 'communication',
    name: '沟通助手',
    role: 'Communication Agent · 消息发送',
    description: '把结果转成合适的消息，并通过工作台或微信适配器交付。',
    initials: '沟',
    color: '#d9f1f4',
    accent: '#278c98',
    icon: 'message',
    skills: ['消息编排', '群组路由', '渠道适配'],
    state: 'idle',
    completedTasks: 57,
  },
]

export const agentMap = Object.fromEntries(agents.map((agent) => [agent.id, agent])) as Record<AgentId, Agent>

const completedReportSteps: PlanStep[] = [
  { id: 'seed-1', agentId: 'supervisor', title: '理解目标并生成计划', description: '识别任务类型：周报生成', phase: 'planning', group: 0, status: 'done', duration: '0.4s', output: '已确定 5 个协作节点' },
  { id: 'seed-2', agentId: 'project', title: '聚合项目进展', description: '读取 6 个项目的里程碑与风险', phase: 'parallel', group: 1, status: 'done', duration: '1.8s', output: '完成 6/6 个项目同步' },
  { id: 'seed-3', agentId: 'data', title: '分析本周业务指标', description: '对比本周与上周核心指标', phase: 'parallel', group: 1, status: 'done', duration: '2.1s', output: '识别 3 个关键趋势' },
  { id: 'seed-4', agentId: 'knowledge', title: '检索历史周报与会议纪要', description: '为结论补充企业上下文和来源', phase: 'parallel', group: 1, status: 'done', duration: '1.3s', output: '匹配 8 条可信来源' },
  { id: 'seed-5', agentId: 'writer', title: '生成管理层周报', description: '将结构化结果组织成简洁汇报', phase: 'synthesis', group: 2, status: 'done', duration: '2.5s', output: '已生成 1,248 字初稿' },
  { id: 'seed-6', agentId: 'reviewer', title: '审核事实与表达', description: '核验数字、来源和结论完整性', phase: 'review', group: 3, status: 'done', duration: '1.1s', output: '通过 · 可信度 96%' },
  { id: 'seed-7', agentId: 'communication', title: '发送至项目群', description: '将最终结果交付给项目成员', phase: 'delivery', group: 4, status: 'working', duration: '—' },
]

export const seededTasks: WorkspaceTask[] = [
  {
    id: 'task-001',
    title: '生成本周项目周报并同步项目群',
    prompt: '帮我整理这周项目进展，生成周报，然后发给项目群。',
    status: 'running',
    progress: 82,
    createdAt: '今天 09:18',
    updatedAt: '刚刚',
    currentAgent: 'communication',
    agents: ['supervisor', 'project', 'data', 'knowledge', 'writer', 'reviewer', 'communication'],
    steps: completedReportSteps,
    activities: [
      { id: 'a-1', agentId: 'supervisor', message: '完成任务拆解，已启动 3 个并行节点', time: '09:18', tone: 'success' },
      { id: 'a-2', agentId: 'project', message: '已同步 6 个项目的里程碑和风险状态', time: '09:19', tone: 'success' },
      { id: 'a-3', agentId: 'data', message: '发现本周交付效率提升 18.6%', time: '09:19', tone: 'success' },
      { id: 'a-4', agentId: 'reviewer', message: '审核通过，报告可信度 96%', time: '09:20', tone: 'success' },
      { id: 'a-5', agentId: 'communication', message: '正在将报告发送至「AI Workspace 项目群」', time: '09:20' },
    ],
    feedback: undefined,
    iteration: 1,
    channel: 'workspace',
  },
  {
    id: 'task-002',
    title: '准备明天的客户会议 Brief',
    prompt: '帮我准备明天的客户会议，整理客户历史和上次会议纪要。',
    status: 'completed',
    progress: 100,
    createdAt: '今天 08:42',
    updatedAt: '今天 08:49',
    agents: ['supervisor', 'meeting', 'document', 'knowledge', 'writer', 'reviewer'],
    steps: [
      { id: 'm-1', agentId: 'supervisor', title: '理解目标并生成计划', description: '识别会议准备任务', phase: 'planning', group: 0, status: 'done', duration: '0.3s' },
      { id: 'm-2', agentId: 'document', title: '整理上次会议纪要', description: '提取决策、异议和行动项', phase: 'parallel', group: 1, status: 'done', duration: '1.4s' },
      { id: 'm-3', agentId: 'knowledge', title: '检索客户相关资料', description: '匹配客户历史与产品资料', phase: 'parallel', group: 1, status: 'done', duration: '1.8s' },
      { id: 'm-4', agentId: 'meeting', title: '梳理会议议程', description: '根据上下文生成讨论重点', phase: 'synthesis', group: 2, status: 'done', duration: '1.2s' },
      { id: 'm-5', agentId: 'writer', title: '生成会议 Brief', description: '生成会前可读的简报', phase: 'synthesis', group: 2, status: 'done', duration: '1.6s' },
      { id: 'm-6', agentId: 'reviewer', title: '审核 Brief', description: '检查客户信息和表达风险', phase: 'review', group: 3, status: 'done', duration: '0.8s' },
    ],
    activities: [
      { id: 'b-1', agentId: 'supervisor', message: '完成会议准备计划', time: '08:42', tone: 'success' },
      { id: 'b-2', agentId: 'document', message: '提取 4 项待跟进事项', time: '08:44', tone: 'success' },
      { id: 'b-3', agentId: 'reviewer', message: 'Brief 已审核通过', time: '08:49', tone: 'success' },
    ],
    result: {
      title: '客户会议 Brief 已准备完成',
      summary: '基于 4 份企业资料和 1 次会议纪要，整理出一份 6 分钟可读的会前简报。',
      bullets: ['明确本次会议的 3 个核心目标', '标记客户上次提出的 2 项待解决问题', '生成可直接使用的议程和提问建议'],
      metrics: [{ label: '引用资料', value: '5 份' }, { label: '可信度', value: '94%' }, { label: '阅读时长', value: '6 min' }],
    },
    iteration: 1,
    channel: 'workspace',
  },
  {
    id: 'task-003',
    title: '分析 7 月销售数据并定位异常',
    prompt: '分析 7 月销售数据，告诉我增长来源和需要关注的异常。',
    status: 'completed',
    progress: 100,
    createdAt: '昨天 16:10',
    updatedAt: '昨天 16:15',
    agents: ['supervisor', 'data', 'knowledge', 'writer', 'reviewer'],
    steps: [
      { id: 's-1', agentId: 'supervisor', title: '理解目标并生成计划', description: '识别数据分析任务', phase: 'planning', group: 0, status: 'done', duration: '0.3s' },
      { id: 's-2', agentId: 'data', title: '计算销售核心指标', description: '聚合销售额、客户数与退款率', phase: 'parallel', group: 1, status: 'done', duration: '1.9s' },
      { id: 's-3', agentId: 'knowledge', title: '补充业务口径', description: '读取指标定义和区域资料', phase: 'parallel', group: 1, status: 'done', duration: '1.1s' },
      { id: 's-4', agentId: 'writer', title: '生成分析结论', description: '整理增长来源与风险提示', phase: 'synthesis', group: 2, status: 'done', duration: '1.7s' },
      { id: 's-5', agentId: 'reviewer', title: '检查数字与结论', description: '核验数据口径和异常判断', phase: 'review', group: 3, status: 'done', duration: '0.9s' },
    ],
    activities: [
      { id: 'c-1', agentId: 'data', message: '已完成 12,864 条订单聚合', time: '16:11', tone: 'success' },
      { id: 'c-2', agentId: 'data', message: '识别华南区域退款率异常上升', time: '16:12', tone: 'warning' },
      { id: 'c-3', agentId: 'reviewer', message: '分析结果已通过口径审核', time: '16:15', tone: 'success' },
    ],
    result: {
      title: '7 月销售分析已完成',
      summary: '销售额环比增长 12.8%，增长主要来自华南区域和 A 产品线；深圳退款率需要跟进。',
      bullets: ['华南区域贡献新增销售额的 46%', 'A 产品转化率较上月提升 8.4%', '深圳区域退款率上升 4.1%，建议核查履约环节'],
      metrics: [{ label: '订单样本', value: '12,864' }, { label: '核心指标', value: '18 项' }, { label: '可信度', value: '98%' }],
    },
    iteration: 1,
    channel: 'schedule',
  },
]

export const navGroups = [
  {
    label: '工作空间',
    items: [
      { key: 'dashboard', label: '工作台', icon: 'grid' },
      { key: 'team', label: 'AI 团队', icon: 'bot', badge: '8' },
      { key: 'tasks', label: '任务中心', icon: 'tasks', badge: '3' },
    ],
  },
  {
    label: '企业能力',
    items: [
      { key: 'knowledge', label: '知识库', icon: 'book' },
      { key: 'documents', label: '文档', icon: 'file' },
      { key: 'analytics', label: '数据分析', icon: 'chart' },
      { key: 'meetings', label: '会议', icon: 'calendar' },
      { key: 'messages', label: '通讯助手', icon: 'message' },
    ],
  },
] as const
